# Generated by Django 2.1.5 on 2019-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190630_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=True, to='lists.List'),
        ),
    ]
